export const PEOPLE_LIST_REQUEST = "PEOPLE_LIST_REQUEST";
export const PEOPLE_LIST_SUCCESS = "PEOPLE_LIST_SUCCESS";
export const PEOPLE_LIST_FAIL = "PEOPLE_LIST_FAIL";

export const PEOPLE_DETAILS_REQUEST = "PEOPLE_DETAILS_REQUEST";
export const PEOPLE_DETAILS_SUCCESS = "PEOPLE_DETAILS_SUCCESS";
export const PEOPLE_DETAILS_FAIL = "PEOPLE_LIST_DETAILS_FAIL";
